server:
  port: 8070
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:customer-db
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"