eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
spring:
  application:
    name: customer
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/bill?createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: turtools
application:
  config:
    customer-url:  http://localhost:8070/api/v1/customer
    inventory-url:  http://localhost:8060/api/v1/inventory
